CREATE TABLE IF NOT EXISTS ESTADOS(
	EST_NOME VARCHAR (40),
	EST_SIGLA CHAR(2) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CIDADES(
	CID_CODIGO SERIAL PRIMARY KEY,
	CID_NOME VARCHAR (40),
	EST_SIGLA CHAR(2),
	CONSTRAINT FK_ESTADO FOREIGN KEY (EST_SIGLA) REFERENCES ESTADOS (EST_SIGLA)
	ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ENDERECOS(
	END_ID SERIAL PRIMARY KEY,
	END_CEP CHAR(9),
	END_COMPLEMENTO VARCHAR (20),
	END_BAIRRO VARCHAR (40),
	END_LOGRADOURO VARCHAR (50),
	END_NUMERO CHAR(7),
	CID_CODIGO INT,
	CONSTRAINT FK_CIDADES FOREIGN KEY (CID_CODIGO) REFERENCES CIDADES (CID_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
	FUN_CODIGO SERIAL PRIMARY KEY,
	END_ID INT,
	FUN_NOME VARCHAR (40),
	FUN_DATA_CADASTRO DATE DEFAULT CURRENT_DATE,
	FUN_CPF CHAR (14),
	FUN_RG CHAR (13),
	FUN_CTPS CHAR (20),
	TEL_NUMERO CHAR (14),
	CEL_NUMERO CHAR (14),
	CONSTRAINT FK_ENDERECO1 FOREIGN KEY (END_ID) REFERENCES ENDERECOS (END_ID)
	ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT unique_pk_func UNIQUE (FUN_CPF)
);

CREATE TABLE IF NOT EXISTS LOGIN(
	LOG_CODIGO SERIAL PRIMARY KEY,
	LOG_SENHA VARCHAR (40) DEFAULT '123',
	LOG_NOME VARCHAR (40),
	FUN_CODIGO INT,
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (FUN_CODIGO) REFERENCES FUNCIONARIOS (FUN_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT unique_pk UNIQUE (LOG_NOME)
);

CREATE TABLE IF NOT EXISTS PROPRIETARIOS(
	PRO_CODIGO SERIAL PRIMARY KEY,
	PRO_NOME VARCHAR (40),
	PRO_RG CHAR (13),
	PRO_NASCIMENTO DATE,
	PRO_CPF CHAR (14),
	TEL_NUMERO CHAR (14),
	CEL_NUMERO CHAR (14),
	END_ID INT,
	CONSTRAINT FK_ENDERECO2 FOREIGN KEY (END_ID) REFERENCES ENDERECOS (END_ID)
	ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT unique_pk_pro UNIQUE (PRO_CPF)
);


CREATE TABLE IF NOT EXISTS QUADRAS (
	TUM_QUADRA CHAR(3) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS LETRAS (
	LET_CODIGO SERIAL PRIMARY KEY,
	LET_LETRA CHAR (3),
	LET_QUADRA CHAR (3),
	CONSTRAINT FK_QUADRA FOREIGN KEY (LET_QUADRA) REFERENCES QUADRAS (TUM_QUADRA)
	ON UPDATE CASCADE ON DELETE SET NULL,
	UNIQUE (LET_LETRA,LET_QUADRA)
);

CREATE TABLE IF NOT EXISTS CHAPAS (
	CHA_CODIGO SERIAL PRIMARY KEY,
	CHA_CHAPA CHAR(10),
	CHA_LETRA INT,
	PRO_CODIGO INT,
		CONSTRAINT FK_PROPRIETARIO2 FOREIGN KEY (PRO_CODIGO)  REFERENCES PROPRIETARIOS (PRO_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL,
		CONSTRAINT FK_LETRA FOREIGN KEY (CHA_LETRA)  REFERENCES LETRAS (LET_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL,
	UNIQUE (CHA_CHAPA,CHA_LETRA)
	
);

CREATE TABLE IF NOT EXISTS VENDAS(
	VEN_CODIGO SERIAL PRIMARY KEY,
	VEN_DATA DATE,
	CHA_CODIGO INT,
	PRO_CODIGO INT,
	CONSTRAINT FK_CHAPA FOREIGN KEY (CHA_CODIGO)  REFERENCES CHAPAS (CHA_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT FK_PROPRIETARIO3 FOREIGN KEY (PRO_CODIGO)  REFERENCES PROPRIETARIOS (PRO_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS OBITOS(
	OBI_CODIGO SERIAL PRIMARY KEY,
	OBI_PROTOCOLO CHAR (15),
	OBI_GUIA VARCHAR (20),
	OBI_MAE VARCHAR (40),
	OBI_CAUSA_MORTE TEXT,
	OBI_PAI VARCHAR (40),
	OBI_NOME VARCHAR (40),
	OBI_IDADE CHAR (3),
	OBI_DATA DATE,
	OBI_MEDICO VARCHAR (40),
	OBI_NUMERO_DOCUMENTO CHAR (9),
	CID_CODIGO INT,
	CHA_CODIGO INT,
	CONSTRAINT FK_CIDADES2 FOREIGN KEY (CID_CODIGO)  REFERENCES CIDADES (CID_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT FK_CHAPA2 FOREIGN KEY (CHA_CODIGO)  REFERENCES CHAPAS (CHA_CODIGO)
	ON UPDATE CASCADE ON DELETE SET NULL
);


insert into funcionarios (fun_nome) values ('ADMIN');

insert into login (log_nome,log_senha,fun_codigo) values ('ADMIN','ADMIN',(select max(fun_codigo) from funcionarios));