/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.TumuloDAO;
import Modelo.Chapas;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Listar_Tumulos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Tumulos
     */
    DefaultTableModel tmTumulo = new DefaultTableModel(null, new String[]{"Quadra", "Letra", "Chapa", "Proprietário"});
    //List de uma classe do modelo para utilização na tabela;
    List<Chapas> chapas;//List de uma classe do modelo para utilização na tabela;
    ListSelectionModel lsmTumulo;
    TumuloDAO tdao;

    public Listar_Tumulos() {
        super("SIGEN - Listagem de Túmulos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jRBPesquisar = new javax.swing.JRadioButton();
        jRBLimpar = new javax.swing.JRadioButton();
        jLEmpresa = new javax.swing.JLabel();
        jLVersao = new javax.swing.JLabel();

        setClosable(true);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(tmTumulo);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listagem de Túmulos");

        jRBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRBPesquisar.setText("Pesquisar");
        jRBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPesquisarActionPerformed(evt);
            }
        });

        jRBLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRBLimpar.setText("Limpar");
        jRBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLimparActionPerformed(evt);
            }
        });

        jLEmpresa.setText("NBNG. Todos os direitos reservados.");

        jLVersao.setText("Versão: 1.4.6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBPesquisar)
                            .addComponent(jRBLimpar))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVersao))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jRBLimpar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVersao)
                    .addComponent(jLEmpresa)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPesquisarActionPerformed
        if (jRBPesquisar.isSelected()) {
            jRBLimpar.setSelected(false);

            tdao = new TumuloDAO();
            chapas = tdao.listarTumulos();
            while (tmTumulo.getRowCount() > 0) {
                tmTumulo.removeRow(0);
            }
            String[] linha = new String[]{null, null, null, null};
            for (int i = 0; i < chapas.size(); i++) {
                tmTumulo.addRow(linha);
                tmTumulo.setValueAt(chapas.get(i).getLetra().getQuadra().getQuadra(), i, 0);
                tmTumulo.setValueAt(chapas.get(i).getLetra().getLetra(), i, 1);
                tmTumulo.setValueAt(chapas.get(i).getChapa(), i, 2);
                tmTumulo.setValueAt(chapas.get(i).getProprietario().getPro_nome(), i, 3);
            }

        }
    }//GEN-LAST:event_jRBPesquisarActionPerformed

    private void jRBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLimparActionPerformed
        if (jRBLimpar.isSelected()) {
            jRBPesquisar.setSelected(false);
            while (tmTumulo.getRowCount() > 0) {
                tmTumulo.removeRow(0);
            }
        }
    }//GEN-LAST:event_jRBLimparActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEmpresa;
    private javax.swing.JLabel jLVersao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBLimpar;
    private javax.swing.JRadioButton jRBPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
